ALTER TABLE nodes ADD COLUMN storage_gib INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN interface_limit INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN process_limit INTEGER NOT NULL DEFAULT 0;
